package com.llmcr.service.review;

import java.util.List;

import com.llmcr.agent.InterpretationAgent.InterpretationAgentOutput;
import com.llmcr.agent.PlanningAgent.PlanningAgentOutput;

public final class MockReviewData {
    public static final String MOCK_DIFFPATH = "../_datasets/test/PR5979.diff";

    public static final InterpretationAgentOutput MOCK_INTERPRETATION = new InterpretationAgentOutput(
            "In `DefaultChatClient` and `DefaultAroundAdvisorChain`, the `doFinally` and `doOnTerminate`/`doOnCancel` callbacks for stopping the observation in the streaming advisor chain have been updated to use an `AtomicBoolean` to prevent multiple calls to `observation.stop()`. This is to ensure that the observation is stopped only once, even if multiple termination signals are received (e.g., error, finally, cancel). Additionally, in `DefaultAroundAdvisorChain.nextStream`, the `contextView` is now passed to `advisor.adviseStream` which is later used in `ToolCallAdvisor.internalStream` for `ToolCallReactiveContextHolder.setContext` to correctly propagate the parent observation to tool call observations.",
            "The original implementation in `DefaultChatClient` and `DefaultAroundAdvisorChain` had a potential issue where `observation.stop()` could be called multiple times if multiple termination signals (error, finally, cancel) were emitted by the stream. This could lead to incorrect observation reporting or errors. The use of `AtomicBoolean` ensures that `observation.stop()` is called exactly once. The propagation of `contextView` to the `adviseStream` method allows for proper parent observation context to be set for tool call observations, ensuring correct hierarchical tracing of operations involving chat clients, advisors, models, and tools.");

    public static final PlanningAgentOutput MOCK_PLANNING = new PlanningAgentOutput(
            "The user wants a checklist for code review focusing on the provided Java/Spring code changes. I need to create 5-8 concise questions covering compatibility, design, security, functionality, performance, maintainability, and readability, based on the diff and description. The core changes involve fixing a potential issue with multiple `observation.stop()` calls using `AtomicBoolean` and improving observation context propagation for tool calls. The new test case also needs to be considered.\\n\\n1. **`AtomicBoolean` for `observation.stop()`:** This is a key fix addressing potential multiple calls. A question about its correctness and prevention of multiple calls is essential.\\n2. **`contextView` propagation for tool calls:** This is another major change for observation hierarchy. A question about its correct utilization and parent context establishment is needed.\\n3. **Dependency management:** While minor, checking for new imports is good practice.\\n4. **Observation lifecycle:** Ensuring the `AtomicBoolean` logic correctly handles the lifecycle under various termination signals is important for functionality and robustness.\\n5. **Tool call context extraction:** Verifying how `ToolCallAdvisor` uses the propagated context is crucial for the observation fix.\\n6. **Race conditions:** The use of `AtomicBoolean` aims to prevent issues, but a question about potential remaining race conditions is relevant for robustness.\\n7. **Test coverage:** The new test specifically validates the observation order and hierarchy. A question about its adequacy is warranted.\\n8. **Code structure/readability:** The changes introduce `AtomicBoolean` and `Runnable`. A question about clarity or potential complexity could be considered, but the core functional/design aspects are more pressing.\\n\\nI will select the most impactful and specific questions to form the checklist.",
            List.of(
                    "Does the use of `AtomicBoolean` correctly prevent multiple `observation.stop()` calls in streaming scenarios across `DefaultChatClient` and `DefaultAroundAdvisorChain`?",
                    "Is the `contextView` propagation to `advisor.adviseStream` in `DefaultAroundAdvisorChain` correctly utilized by `ToolCallAdvisor` to establish parent observations for tool calls?",
                    "Are new dependencies on `java.util.concurrent.atomic.AtomicBoolean` appropriately handled and imported in the modified files?",
                    "Does the introduction of `AtomicBoolean` and `Runnable stopObservation` in `DefaultChatClient` and `DefaultAroundAdvisorChain` maintain the intended observation lifecycle for both successful and erroneous stream terminations?",
                    "Does the change ensure that tool call observations correctly inherit their parent observation context from the advisor chain via the propagated `contextView`?",
                    "Are there any potential race conditions introduced by the new `AtomicBoolean` logic in concurrent streaming scenarios?",
                    "Does the `ToolCallAdvisor` correctly extract and utilize the `ContextView` for `ToolCallReactiveContextHolder.setContext` to maintain observation hierarchy?",
                    "Does the new test `ChatClientStreamingObservationOrderTests` adequately cover the intended observation start/stop order and parent relationships for streaming with tool calls?"));
}
