services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ragdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  faiss:
    build: ./faiss_service
    container_name: faiss
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./faiss_service/app:/app/app
      - faiss_data:/app/faiss_index

volumes:
  mariadb_data:
  faiss_data:
