services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ragdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  faiss:
    build: ./faiss_service
    container_name: faiss
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./faiss_service/app/data:/app/app/data

  # llama-swap:
  #   image: ghcr.io/mostlygeek/llama-swap:cpu
  #   platform: linux/amd64
  #   container_name: llama-swap
  #   restart: unless-stopped
  #   command: ["-config", "/app/config.yaml", "-listen", "0.0.0.0:8080"]
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./llama-swap.yml:/app/config.yaml:ro
  #     - ./models:/models

volumes:
  mariadb_data:
