package com.llmcr.agent.base;

import java.util.HashMap;
import java.util.Map;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.ChatClient.ChatClientRequestSpec;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.ai.template.st.StTemplateRenderer;
import com.llmcr.agent.logging.AgentContextHolder;
import com.llmcr.agent.logging.AgentLoggerAdvisor;
import com.llmcr.service.ModelClientFactory;
import com.llmcr.util.StringUtils;

/**
 * Base class for agents that interact with a language model via ChatClient.
 * 
 * @param <I> Input type for the agent
 * @param <R> Raw response type from the model, outputConverter will convert the
 *            raw response to this type
 * @param <O> Final output type of the agent
 */
public abstract class Agent<I, R, O> {

    protected final String chatProviderName;
    protected final String chatModelName;
    protected final ChatClient chatClient;
    protected final BeanOutputConverter<R> outputConverter;
    protected static final int MAX_RETRY_COUNT = 3;

    /**
     * If outputConverter is provided, the agent will use it to convert the raw
     * model response to type R. If outputConverter is null, the raw response will
     * be cast to R (which may cause a ClassCastException if R is not String).
     */
    protected Agent(String chatProviderName, String chatModelName,
            ModelClientFactory modelClientFactory, BeanOutputConverter<R> outputConverter) {
        this.chatProviderName = chatProviderName;
        this.chatModelName = chatModelName;
        this.chatClient = modelClientFactory.createChatClient(chatProviderName, chatModelName);
        this.outputConverter = outputConverter;
    }

    /**
     * Return the prompt template for this agent. The template should use
     * "<" and ">" to wrap variables.
     * 
     * If a "format_instructions" placeholder is provided, the agent will
     * automatically append the format instruction generated by outputConverter to
     * the prompt.
     */
    protected abstract String getPromptTemplate();

    /**
     * Return a map of variable names to values for rendering the prompt template.
     */
    protected abstract Map<String, Object> getPromptVariables(I input);

    /**
     * This method can be overridden by subclasses to customize the
     * ChatClientRequestSpec before making the API call. For example, subclasses can
     * add specific advisors, set temperature or max tokens, etc. By default, it
     * returns the requestSpec without any modifications.
     */
    protected ChatClientRequestSpec customizeRequest(ChatClientRequestSpec requestSpec) {
        return requestSpec;
    }

    @SuppressWarnings("unchecked")
    protected R convertRawResponse(String rawResponse) {

        int attempt = 0;
        while (true) {
            try {
                String cleaned = StringUtils.cleanMarkdownCodeBlocks(rawResponse);
                return outputConverter != null ? outputConverter.convert(cleaned) : (R) cleaned;
            } catch (Exception e) {
                attempt++;
                if (attempt >= MAX_RETRY_COUNT) {
                    break;
                }

                ChatClientRequestSpec retryRequest = chatClient
                        .prompt("Fix this invalid JSON. Return ONLY valid JSON.")
                        .advisors(new AgentLoggerAdvisor("OutputFixAgent"));

                retryRequest.user(rawResponse);
                rawResponse = retryRequest.call().content();
            }
        }
        throw new RuntimeException("Failed to convert model response after " + MAX_RETRY_COUNT + " attempts");
    }

    protected abstract O convertModelResponse(R modelResponse);

    protected O doExecute(I input) {
        String prompt = buildPrompt(input);
        ChatClientRequestSpec baseRequest = chatClient
                .prompt(prompt)
                .advisors(new AgentLoggerAdvisor(this.getClass().getSimpleName()));

        ChatClientRequestSpec requestSpec = customizeRequest(baseRequest);
        String rawResponse = requestSpec.call().content();

        R modelResponse = convertRawResponse(rawResponse);
        return convertModelResponse(modelResponse);
    }

    protected String buildPrompt(I input) {
        Map<String, Object> variables = new HashMap<>();
        variables.putAll(getPromptVariables(input));
        variables.put("format_instructions", outputConverter != null ? outputConverter.getFormat() : "");

        return PromptTemplate.builder()
                .renderer(StTemplateRenderer.builder().startDelimiterToken('<').endDelimiterToken('>').build())
                .template(getPromptTemplate())
                .build()
                .render(variables);
    }

    public O execute(I input) {
        AgentContextHolder.beginContext(this.getClass().getSimpleName(), chatModelName);
        try {
            return doExecute(input);
        } finally {
            AgentContextHolder.endContext();
        }
    }
}
