# llmcr.agent.interpretation.chat.provider=google
# llmcr.agent.interpretation.chat.model=gemini-2.5-flash-lite

# llmcr.agent.planning.chat.provider=google
# llmcr.agent.planning.chat.model=gemini-2.5-flash-lite

# llmcr.agent.computation.chat.provider=openai
# llmcr.agent.computation.chat.model=Phi-4-Mini

llmcr.agent.retrieval.chat.provider=openai
llmcr.agent.retrieval.chat.model=LFM2.5-1.2B

# llmcr.agent.summary.chat.provider=openai
# llmcr.agent.summary.chat.model=Phi-4-Mini