package com.llmcr.agent;

import java.util.Map;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.ChatClient.ChatClientRequestSpec;
import org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.ai.template.st.StTemplateRenderer;

/**
 * Base class for agents that interact with a language model via ChatClient.
 * 
 * @param <I> Input type for the agent
 * @param <R> Raw response type from the model, outputConverter will convert the
 *            raw response to this type
 * @param <O> Final output type of the agent
 */
public abstract class Agent<I, R, O> {

    protected final ChatClient chatClient;
    protected final BeanOutputConverter<R> outputConverter;

    protected Agent(ChatClient chatClient, BeanOutputConverter<R> outputConverter) {
        this.chatClient = chatClient;
        this.outputConverter = outputConverter;
    }

    /**
     * Return the prompt template for this agent. The template should use
     * "<" and ">" to wrap variables.
     * 
     * If a "format_instructions" placeholder is provided, the agent will
     * automatically append the format instruction generated by outputConverter to
     * the prompt.
     */
    protected abstract String getPromptTemplate();

    /**
     * Return a map of variable names to values for rendering the prompt template.
     */
    protected abstract Map<String, Object> getPromptVariables(I input);

    protected String buildPrompt(I input) {
        Map<String, Object> variables = getPromptVariables(input);
        variables.put("format_instructions", outputConverter.getFormat());

        return PromptTemplate.builder()
                .renderer(StTemplateRenderer.builder().startDelimiterToken('<').endDelimiterToken('>').build())
                .template(getPromptTemplate())
                .build()
                .render(variables);
    }

    /**
     * This method can be overridden by subclasses to customize the
     * ChatClientRequestSpec before making the API call. For example, subclasses can
     * add specific advisors, set temperature or max tokens, etc. By default, it
     * returns the requestSpec without any modifications.
     */
    protected ChatClientRequestSpec customizeRequest(ChatClientRequestSpec requestSpec) {
        return requestSpec;
    }

    protected abstract O convertModelResponse(R modelResponse);

    public O execute(I input) {
        String prompt = buildPrompt(input);
        ChatClientRequestSpec baseRequest = chatClient
                .prompt(prompt)
                .advisors(new SimpleLoggerAdvisor());

        ChatClientRequestSpec requestSpec = customizeRequest(baseRequest);
        // TODO: log raw request here

        String rawResponse = requestSpec.call().content();
        // TODO: log raw response here

        // TODO: fallback parser if outputConverter fails
        R modelResponse = outputConverter.convert(rawResponse);
        return convertModelResponse(modelResponse);
    }
}
