spring.application.name=llmcr
spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/ragdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Faiss
faiss.service.url=http://localhost:8000

# Gemini Settings
# spring.ai.google.genai.api-key=${GOOGLE_GEMINI_API_KEY}
# spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Ollama Settings
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=lfm2.5-thinking:latest
spring.ai.ollama.embedding.options.model=embeddinggemma:300m

# logging
logging.pattern.console=[%d{yyyy-MM-dd HH:mm:ss}] [%p] %logger{0}: %msg%n
logging.level.root=INFO