spring.application.name=llmcr

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/ragdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# FAISS
llmcr.faiss.url=http://localhost:8000

# Disable Spring AI auto-configuration
spring.ai.chat.client.enabled=false
spring.ai.embedding.client.enabled=false

# Model Providers
spring.ai.google.genai.api-key=${GOOGLE_GEMINI_API_KEY}

# Models
llmcr.chat.small.openapi.url=http://localhost:10001
llmcr.chat.provider=openapi
llmcr.chat.small.model=lfm2.5-1.2b

llmcr.chat.large.openapi.url=none
llmcr.chat.provider=google.genai
llmcr.chat.large.model=gemini-3.1-pro

llmcr.embedding.openapi.url=http://localhost:10002
llmcr.embedding.provider=openapi
llmcr.embedding.model=harrier-0.6b

llmcr.reranking.openapi.url=http://localhost:10003
llmcr.reranking.provider=openapi
llmcr.reranking.model=zerank-2

# Optional modules
llmcr.reflection.enable=false
llmcr.reflection.iterations=3

# Logging
logging.pattern.console=[%d{yyyy-MM-dd HH:mm:ss}] [%p] %logger{0}: %msg%n
logging.level.root=INFO